# This is a basic workflow to help you get started with Actions

name: Compile SPAdes for Colab

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    # Triggers the worflow on new tag
    tags:        
      - '*'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Run with Colab runtime Docker image
    container:
      image: us-docker.pkg.dev/colab-images/public/runtime:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download SPAdes release
        run: wget http://cab.spbu.ru/files/release${{ github.ref }}/SPAdes-${{ github.ref }}.tar.gz
        
      - name: Extract SPAdes release
        run: tar -xzf SPAdes-${{ github.ref }}.tar.gz
        
      - name: Compile SPAdes
        run: ./SPAdes-${{ github.ref }}/spades_compile.sh
        
      - name: Create tarball
        run: tar -czf ./SPAdes-${{ github.ref }}-Linux.tar.gz ./SPAdes-${{ github.ref }}/bin ./SPAdes-${{ github.ref }}/share

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./SPAdes-${{ github.ref }}-Linux.tar.gz 
